### ISSUE TITLE
PYTHON 3 - Migration

### ISSUE THREAD

**Issue by sdonovan1985** [atlanticwave-sdx/atlanticwave-proto#109]
From the Audit report, part 1: 
> AW-SDX is based on Python 2 which is scheduled to be sunsetted on January 1, 2020 (https://www.python.org/dev/peps/pep-0373/). Steps should be taken to port the codebase to be Python 3 compliant such that it maintains proper package support beyond the Python 2 end of life date (https://docs.python.org/3/howto/pyporting.html).

**Comment by sdonovan1985** [comment]
I started working on this again yesterday. I tried to run the code after the the first check-in yesterday. Failed miserably in Python2 nearly immediately. 

The problem is one of the common ones called out in the futurize info (http://python-future.org/automatic_conversion.html#example-error), I'm not sure what the deal is, bu I've been looking since yesterday to try to understand what's wrong. 

I have no idea.

**Comment by sdonovan1985** [comment]
The issue I'm seeing does appear to be related to nosetests, which really likes to muck about with the sys.path, which is hugely annoying.

When I run all tests: fails.  

```
sudo PYTHONPATH=$PYTHONPATH nosetests --with-xunit --all-modules --traverse-namespace \  
  --with-coverage --cover-package=localctlr \  
  --cover-inclusive
```  
Fails

```
sudo PYTHONPATH=$PYTHONPATH nosetests --with-xunit --all-modules --traverse-namespace \  
  --with-coverage \  
  --cover-inclusive localctlr/tests/  
```  
Fails

```
sudo PYTHONPATH=$PYTHONPATH nosetests --with-xunit --all-modules --traverse-namespace \  
  --with-coverage \  
  --cover-inclusive localctlr/tests/test_ControllerInterface.py:BasicTests  
```  
Works

This is just bizarre. The path for the last two tests are below:

```
['/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/lib',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/lib',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/lib',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/lib',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/lib',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/lib',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/lib',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/lib',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/lib',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/lib',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/bin',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/lib/python2.7',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/lib/python2.7/plat-x86_64-linux-gnu',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/lib/python2.7/lib-tk',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/lib/python2.7/lib-old',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/lib/python2.7/lib-dynload',  
'/usr/lib/python2.7',  
'/usr/lib/python2.7/plat-x86_64-linux-gnu',  
'/usr/lib/python2.7/lib-tk',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/local/lib/python2.7/site-packages',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/lib/python2.7/site-packages']
```
```
['/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/lib',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/lib',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/bin',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/lib/python2.7',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/lib/python2.7/plat-x86_64-linux-gnu',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/lib/python2.7/lib-tk',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/lib/python2.7/lib-old',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/lib/python2.7/lib-dynload',  
'/usr/lib/python2.7',  
'/usr/lib/python2.7/plat-x86_64-linux-gnu',  
'/usr/lib/python2.7/lib-tk',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/local/lib/python2.7/site-packages',  
'/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/lib/python2.7/site-packages']
```

It's easier to see it side by side, but the important part is the extra 8 copies of /lib in the former. This ought not to make any difference. One thing that is missing: . should be part of the sys.path...

In any case, the failure that we're seeing in all the failed cases is:
```
Traceback (most recent call last):
  File "/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/bin/ryu-manager", line 11, in <module>
    sys.exit(main())
  File "/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/local/lib/python2.7/site-packages/ryu/cmd/manager.py", line 78, in main
    app_mgr.load_apps(app_lists)
  File "/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/local/lib/python2.7/site-packages/ryu/base/app_manager.py", line 415, in load_apps
    cls = self.load_app(app_cls_name)
  File "/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/local/lib/python2.7/site-packages/ryu/base/app_manager.py", line 392, in load_app
    mod = utils.import_module(name)
  File "/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/.pyenv/local/lib/python2.7/site-packages/ryu/utils.py", line 102, in import_module
    mod = importlib.import_module(name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/jenkins/workspace/sdx-test-coverage-python3port-python2tests/localctlr/RyuTranslateInterface.py", line 20, in <module>
    from .oftables import *
ValueError: Attempted relative import in non-package
```

This is sys.path related. If I remove the `.` from `.oftables`, it works. It may (I"m not sure, haven't tested it yet) break in Python3. 

This brings me back to the question: Should I just say screw it and break Python2 compatibility and go to Python3 only?

**Comment by sdonovan1985** [comment]
https://docs.python.org/dev/tutorial/modules.html#intra-package-references

The last line in this link is *very* important. I have been manually trying to run SDXController locally on my laptop. The imports of all the submodules of the SDXController *must* be imported as follows:

```
from sdxctlr.AuthenticationInspector import *
```

I'm going to still need to figure out the `import *` changes, but this is a start.

**Comment by sdonovan1985** [comment]
Ok, working through that is going alright.  I ran into an issue where the Singleton work isn't going particularly well. 

In the following logs, right at the beginning you can see that the TopologyManager and PolicyManager are both initialized. Now, down below at the PolicyManager is initialized *again*. The failure at the very end is during `TopologyManager.__init__()`. These shouldn't be called. They're supposed to be Singletons and *never* reinitialized. This is either a) related to the import changes in Python3 *or* Singleton being broken. 

```
(.pyenv) Seans-MBP-2:sdxctlr sdonovan$ python3 SDXController.py -m ../configuration/twoswitch-onelc/twoswitch-onelc-noncorsa.manifest -N
Namespace(database=':memory:', host='0.0.0.0', lcport=5555, manifest='../configuration/twoswitch-onelc/twoswitch-onelc-noncorsa.manifest', port=5000, shib=False, sport=5001, topo=False)

../configuration/twoswitch-onelc/twoswitch-onelc-noncorsa.manifest
{'shortname': 'oneLC', 'credentials': 'pwd', 'location': '0,0', 'lcip': '127.0.0.1', 'internalconfig': {'ryucxninternalport': 55780, 'openflowport': 6680}, 'switchinfo': [{'name': 'br1', 'friendlyname': 'br1', 'ip': '127.0.0.1', 'dpid': '1', 'brand': 'Open vSwitch', 'model': '2.3.0', 'portinfo': [{'portnumber': 1, 'speed': 8000000000, 'destination': 'atl'}, {'portnumber': 2, 'speed': 8000000000, 'destination': 'atldtn'}, {'portnumber': 3, 'speed': 8000000000, 'destination': 'br2'}], 'internalconfig': {'corsaurl': '', 'corsatoken': '', 'corsabridge': 'br1', 'corsabwin': 11, 'corsabwout': 12, 'corsaratelimiterbridge': 'br21', 'corsaratelimiterports': [21, 22], 'managementvlan': 4085, 'managementvlanports': [3, 4]}}, {'name': 'br2', 'friendlyname': 'br2', 'ip': '127.0.0.1', 'dpid': '2', 'brand': 'Open vSwitch', 'model': '2.3.0', 'portinfo': [{'portnumber': 1, 'speed': 8000000000, 'destination': 'mia'}, {'portnumber': 2, 'speed': 8000000000, 'destination': 'miadtn'}, {'portnumber': 3, 'speed': 8000000000, 'destination': 'br1'}], 'internalconfig': {'corsaurl': '', 'corsatoken': '', 'corsabridge': 'br2', 'corsabwin': 11, 'corsabwout': 12, 'corsaratelimiterbridge': 'br21', 'corsaratelimiterports': [21, 22], 'managementvlan': 4085, 'managementvlanports': [3, 4]}}], 'operatorinfo': {'organization': 'Georgia Tech/RNOC', 'administrator': 'Sean Donovan', 'contact': 'sdonovan@gatech.edu'}}

2019-10-04 13:44:22,204 sdxcontroller.topologymanager: 4621977024 WARNING  TopologyManager initialized: 0x1089adb10
2019-10-04 13:44:22,205 sdxcontroller.authentication: 4621977024 WARNING  AuthenticationInspector initialized: 0x10988bd10
2019-10-04 13:44:22,205 sdxcontroller.authorization: 4621977024 WARNING  AuthorizationInspector initialized: 0x10988b7d0
2019-10-04 13:44:22,205 sdxcontroller.breakdownengine: 4621977024 WARNING  BreakdownEngine initialized: 0x10988b710
2019-10-04 13:44:22,221 sdxcontroller.policyregistry: 4621977024 WARNING  PolicyRegistry found UserPolicy: /Users/sdonovan/ownCloud/2019-fall/python3/shared/UserPolicy.py
2019-10-04 13:44:22,403 sdxcontroller.policyregistry: 4621977024 WARNING  PolicyRegistry initialized: 0x10988b5d0
2019-10-04 13:44:22,403 sdxcontroller.validityinspector: 4621977024 WARNING  ValidityInspector initialized: 0x109880c10
2019-10-04 13:44:22,403 sdxcontroller.usermanager: 4621977024 CRITICAL Connection to DB: :memory:
2019-10-04 13:44:22,423 sdxcontroller.usermanager: 4621977024 INFO     Failed to load user_table from DB, creating table
2019-10-04 13:44:22,425 sdxcontroller.usermanager: 4621977024 INFO     There are 0 users in the user table
2019-10-04 13:44:22,425 sdxcontroller.usermanager: 4621977024 INFO     Loading users from the Manifest
Sending sdonovan:1234 to AuthenticationInspector
2019-10-04 13:44:22,440 sdxcontroller.authentication: 4621977024 WARNING  AuthenticationInspector initialized: 0x109a04f50
2019-10-04 13:44:22,440 sdxcontroller.authentication: 4621977024 INFO     New user being added to store: sdonovan
2019-10-04 13:44:22,440 sdxcontroller.authorization: 4621977024 WARNING  AuthorizationInspector initialized: 0x109a04f50
Sending jchung:4321 to AuthenticationInspector
2019-10-04 13:44:22,441 sdxcontroller.authentication: 4621977024 WARNING  AuthenticationInspector initialized: 0x109a04bd0
2019-10-04 13:44:22,441 sdxcontroller.authentication: 4621977024 INFO     New user being added to store: jchung
2019-10-04 13:44:22,441 sdxcontroller.authorization: 4621977024 WARNING  AuthorizationInspector initialized: 0x109a04bd0
2019-10-04 13:44:22,441 sdxcontroller.usermanager: 4621977024 WARNING  UserManager initialized: 0x109494250


2019-10-04 13:44:22,441 sdxcontroller.authentication: 4621977024 WARNING  AuthenticationInspector initialized: 0x109a043d0
2019-10-04 13:44:22,441 sdxcontroller.authentication: 4621977024 INFO     New user being added to store: oneLC
2019-10-04 13:44:22,441 sdxcontroller.localctlrmgr: 4621977024 WARNING  LocalControllerManager initialized: 0x1098e4610

2019-10-04 13:44:22,442 sdxcontroller.sdxctlrcxnmgr: 4621977024 WARNING  SDXControllerConnectionManager initialized: 0x109a043d0
2019-10-04 13:44:22,442 sdxcontroller.policyregistry: 4621977024 INFO     PolicyRegistry looking for policies in /Users/sdonovan/ownCloud/2019-fall/python3/shared
2019-10-04 13:44:22,442 sdxcontroller.sdxctlrcxnmgr: 123145332281344 CRITICAL Opening listening socket: 0.0.0.0:5555
2019-10-04 13:44:22,457 sdxcontroller.policyregistry: 4621977024 INFO     PolicyRegistry Found all policy types in /Users/sdonovan/ownCloud/2019-fall/python3/shared
2019-10-04 13:44:22,457 sdxcontroller.policymanager: 4621977024 CRITICAL Connection to DB: :memory:
2019-10-04 13:44:22,458 sdxcontroller.policymanager: 4621977024 INFO     Failed to load policy_table from DB, creating table
2019-10-04 13:44:22,459 sdxcontroller.policymanager: 4621977024 INFO     Failed to load config_table from DB, creating table
Policies present at initialization:
Policy number = 1
2019-10-04 13:44:22,469 sdxcontroller.policymanager: 4621977024 WARNING  PolicyManager initialized: 0x109a04350
2019-10-04 13:44:22,469 sdxcontroller.rest: 4621977024 CRITICAL Opening socket 0.0.0.0:5000
2019-10-04 13:44:22,470 sdxcontroller.rest: 4621977024 WARNING  RestAPI initialized: 0x109b08f90
2019-10-04 13:44:22,470 sdxcontroller.policymanager: 4621977024 CRITICAL Connection to DB: :memory:
2019-10-04 13:44:22,472 sdxcontroller.policymanager: 4621977024 INFO     Failed to load policy_table from DB, creating table
2019-10-04 13:44:22,473 sdxcontroller.policymanager: 4621977024 INFO     Failed to load config_table from DB, creating table
Policies present at initialization:
Policy number = 1
2019-10-04 13:44:22,489 sdxcontroller.policymanager: 4621977024 WARNING  PolicyManager initialized: 0x109b0c410
../manifests/localcontroller.manifest

{'shortname': 'atl', 'credentials': 'atlpw', 'location': 'In the kernel', 'lcip': '10.10.10.10', 'switchinfo': [{'name': 'atl-switch', 'friendlyname': 'Main Atlanta Switch', 'dpid': 1, 'ip': '10.10.10.11', 'brand': 'Open vSwitch', 'model': '2.3.0', 'portinfo': [{'portnumber': 1, 'speed': 1, 'destination': 'mia-switch'}, {'portnumber': 2, 'speed': 1, 'destination': 'Georgia Tech'}], 'rulesaccepted': ['tbd'], 'rulesnotaccepted': ['tbd'], 'reservationsallowed': {'maxtime': '7 days', 'maxbandwidth': '200 Mbps', 'maxports': '3'}}], 'operatorinfo': {'organization': 'Georgia Tech/RNOC', 'administrator': 'Sean Donovan', 'contact': 'sdonovan@gatech.edu'}}

Traceback (most recent call last):
  File "SDXController.py", line 414, in <module>
    sdx = SDXController(False, options)
  File "SDXController.py", line 120, in __init__
    host=options.host, port=options.sport)
  File "/Users/sdonovan/ownCloud/2019-fall/python3/sdxctlr/SenseAPI.py", line 160, in __init__
    self.current_topo = TopologyManager().get_topology()
  File "/Users/sdonovan/ownCloud/2019-fall/python3/sdxctlr/TopologyManager.py", line 100, in __init__
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
    self._import_topology(topology_file)
  File "/Users/sdonovan/ownCloud/2019-fall/python3/sdxctlr/TopologyManager.py", line 199, in _import_topology
    self.topo.node[key]['internalconfig'] = entry['internalconfig']
KeyError: 'internalconfig'
(.pyenv) Seans-MBP-2:sdxctlr sdonovan$ 
```

**Comment by sdonovan1985** [comment]
Aha! Metaclasses in Python2 and 3 are different.

https://stackoverflow.com/questions/6760685/creating-a-singleton-in-python#6798042

I was using the above method for creating a singleton, and hadn't converted over to the Python 3 way of the world. Reran my local test, and it (appears to) work. Need to tidy up and check in and then try running on Jenkins again.

**Comment by sdonovan1985** [comment]
Alright, with that last checkin, Python 2 testing of sdxctrl directory is working. This is a big step.  Most of the changes were related to importing, printing (needs parens; it's a real function), or similar. Now, to move onto the other folders: lib, shared, and localctlr. The first 3 should be pretty straight forward, but localctlr shoudl be a bit of a challenge.

**Comment by sdonovan1985** [comment]
Manually ran Python 3 for sdxctlr successfully.

Python 2 testing of lib is good now. I also ran it manually in Python 3 successfully.

**Comment by sdonovan1985** [comment]
Huh, shared was a freebie in automated Python 2 and manual Python 3.

Next up is localctlr. Which will be terrible.

**Comment by sdonovan1985** [comment]
Ok, started out terribly, as I was trying to run based on the directory, rather than package. Wildly unsuccessful. Weird failures: sometimes things would hang, sometimes everything world works *except* the coverage step... it was really weird.

I tried running just the localctlr package. This worked just fine. I then ran all the packages. Works just fine. 

So, that's Python2. Next up, getting Python 3 + Jenkins to play nice.

**Comment by sdonovan1985** [comment]
Oh, the latest problem is... annoying. 

The DB was spitting out Unicode, which is fine. Python 2 is *very not Unicode* friendly. So, to get around this, we typecast all over the place to str whenever we depickle something. Python 3's pickle doesn't like this, at all. 

So, fixing this is a rather manual process. This will be a while.

**Comment by sdonovan1985** [comment]
Ok, current problem is with the Steiner Tree algorithm. I used a library for Steiner tree generation from [here](https://github.com/xlu29466/PyGibbCAMP/blob/master/SteinerTree.py). It was written 6 years ago, and hasn't been updated.

The problem is described [here](https://stackoverflow.com/questions/22333388/dicts-are-not-orderable-in-python-3). The gist of it is that in Python2, dictionaries are ordered implicitly, while in Python3, that's not the case. So, I'll have to figure out how to a) fix it, or b) replace the algorithm.

**Comment by sdonovan1985** [comment]
That's fun. That worked surprisingly well. Python2 is still good. Python3 is in better shape, though there's plenty more errors (down to 67!) to get through.

**Comment by sdonovan1985** [comment]
Current set of issues is related to [this](https://eli.thegreenplace.net/2012/01/30/the-bytesstr-dichotomy-in-python-3) major change between Python 2 and 3. This is a *great* improvement. Got to fix it though.

**Comment by sdonovan1985** [comment]
That last change appears to have broken Python2. Python 3 is working just as well as before (65 errors/failures!). Going to have to test this a bit better.

**Comment by sdonovan1985** [comment]
So, the last series of changes since the last comment - the reversions, the small changes, etc - were seemingly pointless. The problem appears to be with the cleanup of the tests causing issues. When I made the last checkin, I kicked off an instance of the Python2 tests. This hung in a loop that I have been seeing since last night. I killed the test from the Jenkins console. I sshed into the ssh-slave container, and ran top. It had an instance of nosetests and two instances of ryu-manager running. I killed all of these off, and reran the Python 2 tests, successfully. 

I'm guessing these zombie tests are from the Python3 instance (you know, the one with dozens of errors/failures). So, this issue seems to be cleanedup

**Comment by sdonovan1985** [comment]
Ok, so that last checkin fixed the last set of errors in individual  localctlr/tests/test_*.py files for Python 3 tests.

When I run them collectively, Python 2 works just fine. Python 3, on the other hand, its getting the weird hanging errors that I was experiencing earlier this week. I'm pretty sure this is due to the zombie processes that I mentioned in the most recent comment. WIll continue to work on this later. Need to find out which test set exactly is causing the zombies.

**Comment by sdonovan1985** [comment]
Ok, ran a bunch of tests today. The 39th run, raw file attached below, is all of localctlr/tests. The filtered file is much more useful. It's filtered by logs that have "BEGIN" in them, and the numbers are the length of the sys.path at AtlanticWaveModule creation.

If you look at the filtered, everything's normal up till the test_RyuTranslateInterface tests. Each test runs once. Once test_RyuTranslateInteface tests start, there's duplicates. Why are there duplicates? No clue. 

I tried running all the tests by filename, and this worked just fine. When I had nosetests run the directory, this problem shows up.

[39.txt](https://github.com/atlanticwave-sdx/atlanticwave-proto/files/3773728/39.txt)

[39.filtered.txt](https://github.com/atlanticwave-sdx/atlanticwave-proto/files/3773729/39.filtered.txt)

**Comment by sdonovan1985** [comment]
Just ran test_RyuTranslateInterface.py in Python2. Same result: there's seemingly two calls to each test.

This is just an illusion. There's *two logs*. One in the test function, and one in the generalized function that runs the test (e.g., trans_XXXXX_test()).

**Comment by sdonovan1985** [comment]
Ok, the mess of crap for the past couple of days ended up being due to a logging error: I was trying to log something that simply didn't exist. This looked like a totally different problem, which is why it took so long to figure out.

Now, the current problem that I'm trying to track down is in sdxctlr.tests.test_TopologyManager.SteinerTreeWithLoopTest.test_steiner_tree_with_loop(), wherein The Steiner tree that's being generated isn't deterministic. It's valid, but not compact. Got to figure that out now.

**Comment by sdonovan1985** [comment]
AtlanticWave/SDX was originally written for Python 2, as the OpenFlow library we use, Ryu, was originally Python 2-only. That changed, and Python2 is becoming unsupported.

I have tried to maintain Python2 and Python3 compatibility, but this may not be necessary. As of last month, during a migration between networkx 1.11 to networkx 2.2, Python2 compatibility was broken to handle Steiner Trees in Python3. There is a possibility to keep both Python2 and Python3 working by using an old Python2 compatible library in Python2 and the new version of networkx in Python3. Is it worth it? I don't think so. I think breaking python2 compatibility isn't a bad thing.

The current hiccup I was working on was to get Steiner trees working properly. During tests, the Steiner tree generation was not deterministic, which seems to have something to do with Python3 and the old library we were using. This is why I was migrating to a new version networkx that has Steiner Tree functionality.

I have a VM created that has Jenkins installed that tests both Python2 and Python3. Most things are working - though I won't say all - and I was working my way through running tests on individual sdxctrl files. Attached the the build script that is currently looking at TopologyManager.py.

[python3buildscript.txt](https://github.com/atlanticwave-sdx/atlanticwave-proto/files/3923760/python3buildscript.txt)

**Comment by YufengXin** [comment]
replaced by #155. Finished in the 'develop' branch.
