### ISSUE TITLE
Trying to create a ELAN on a single node blows up

### ISSUE THREAD

**Issue by sdonovan1985** [atlanticwave-sdx/atlanticwave-proto#29]
I attempted to create a ELAN on a single node, and it failed with the error below.

Odds are, there needs to be special casing for when multiple endpoints are on the same node.

[2017-08-24 14:28:57,071] ERROR in app: Exception on /rule/l2m [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sdonovan/fivetable/sdxctlr/RestAPI.py", line 386, in make_L2M
    rule_hash = RuleManager.instance().add_rule(policy)
  File "/home/sdonovan/fivetable/sdxctlr/RuleManager.py", line 130, in add_rule
    breakdown = self._determine_breakdown(rule)
  File "/home/sdonovan/fivetable/sdxctlr/RuleManager.py", line 297, in _determine_breakdown
    breakdown = BreakdownEngine.instance().get_breakdown(rule)
  File "/home/sdonovan/fivetable/sdxctlr/BreakdownEngine.py", line 29, in get_breakdown
    return rule.breakdown_rule(tm, ai)
  File "/home/sdonovan/fivetable/shared/L2MultipointPolicy.py", line 97, in breakdown_rule
    self.tree = tm.find_valid_steiner_tree(nodes, self.bandwidth)
  File "/home/sdonovan/fivetable/sdxctlr/TopologyManager.py", line 396, in find_valid_steiner_tree
    tree = make_steiner_tree(self.topo, nodes)
  File "/home/sdonovan/fivetable/lib/SteinerTree.py", line 89, in make_steiner_tree
    subgraph = make_prim_mst(subgraph, generator)
  File "/home/sdonovan/fivetable/lib/SteinerTree.py", line 142, in make_prim_mst
    firstNode = G.nodes()[0]
IndexError: list index out of range
143.215.29.32 - - [24/Aug/2017 14:28:57] "GET /rule/l2m?starttime=2017-08-12T23:01:50&endtime=2017-09-13T23:20:50&endpoints={%22endpoints%22:[{%22switch%22:%22br1%22,%20%22port%22:1,%20%22vlan%22:1000},{%22switch%22:%22br1%22,%20%22port%22:2,%20%22vlan%22:2000},{%22switch%22:%22br1%22,%20%22port%22:3,%20%22vlan%22:1000}]}&bandwidth=1000 HTTP/1.1" 500 -
^[OA

**Comment by sdonovan1985** [comment]
Running the controller without switches:
python SDXController.py -m ../configuration/single-node/singlenode-noncorsa.manifest -N

Called from Chrome:
http://localhost:5000/rule/l2m?starttime=2017-09-07T23:01:50&endtime=2017-09-13T23:20:50&endpoints={%22endpoints%22:[{%22switch%22:%22br1%22,%20%22port%22:1,%20%22vlan%22:1000},{%22switch%22:%22br1%22,%20%22port%22:1,%20%22vlan%22:2000},{%22switch%22:%22br1%22,%20%22port%22:1,%20%22vlan%22:1000}]}&bandwidth=1000

Notes while I'm working on this bug.

**Comment by sdonovan1985** [comment]
Fixed this bug, tested as above.

What was happening was multiple instances of the same node were being sent down to the Steiner Tree library. It didn't like that. So, just skipped over duplicates when creating the list of nodes that need to be hit by the tree.
