### ISSUE TITLE
Error on removing rule

### ISSUE THREAD

**Issue by sdonovan1985** [atlanticwave-sdx/atlanticwave-proto#49]
I've run into this a few times: removing a rule sometimes results in this issue below: 

```
Receiving Command on sdx_connection
Received : RM_RULE:(2, 5)
Sent     : RM_RULE:(2, 5)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/sdx/dev/localctlr/RyuTranslateInterface.py", line 284, in main_loop
    self.remove_rule(datapath, event)
  File "/home/sdx/dev/localctlr/RyuTranslateInterface.py", line 1218, in remove_rule
    for rule in swrules:
TypeError: 'NoneType' object is not iterable
```
The code this is referencing is below:

```Python
    def remove_rule(self, datapath, sdx_cookie):
        ''' The main loop calls this to handle removing an existing rule.
            This function removes the existing OpenFlow rules associated with
            a given sdx_cookie. '''

        # Remove a rule.
        # Find the OF cookie based on the SDX Cookie
        of_cookie = self._find_OF_cookie(sdx_cookie)

        # Get the Rules based on the it.
        (swcookie, sdxrule, swrules, table) = self._get_rule_in_db(sdx_cookie)
                
        # Remove flows
        for rule in swrules:           #THIS IS 1218
            if type(rule) == TranslatedLCRuleContainer:
                self.remove_flow(datapath, rule)
            elif type(rule) == TranslatedCorsaRuleContainer:
                # Currently, don't have to do anything here.
                pass

        # Remove rule infomation from database
        self._remove_rule_in_db(sdx_cookie)
```

**Comment by sdonovan1985** [comment]
The above commit should help with diagnosing this issue.

**Comment by sdonovan1985** [comment]
I haven't seen this error in over a year. There have been some major updates to the add/remove paths. Going to leave open for now.

**Comment by sdonovan1985** [comment]
Closing this one out.
