### ISSUE TITLE
Persistence - Overlapping login failure

### ISSUE THREAD

**Issue by sdonovan1985** [atlanticwave-sdx/atlanticwave-proto#74]
Ran into a weird issue late last week (first on Thursday), and I figured out how to reproduce it (finally) today.

 - Start LC and SDX - Wait till connection fully established
 - Stop LC
 - Wait till LC failure is seen on SDX and cleaned up (1 heartbeat)
 - Start LC

This will be just fine. 

 - Start LC and SDX - Wait till connection fully established
 - Stop LC
 - *Immediately* start LC
 - Wait one heartbeat, and you'll see the following failure:

``` No rule to remove for sdx_cookie 196
<dataset.persistence.util.ResultIter object at 0x3109110>
2018-03-19 12:30:16,518 localcontroller.ryutranslateinterface: ERROR    Error in remove_rule 196:None
Error in remove_rule 196:None
2018-03-19 12:30:16,519 localcontroller.ryutranslateinterface: ERROR      swcookie: None
  swcookie: None
2018-03-19 12:30:16,519 localcontroller.ryutranslateinterface: ERROR      sdxrule: None
  sdxrule: None
2018-03-19 12:30:16,519 localcontroller.ryutranslateinterface: ERROR      swrules: None
  swrules: None
2018-03-19 12:30:16,519 localcontroller.ryutranslateinterface: ERROR      table: None
  table: None
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/sdx/dev/localctlr/RyuTranslateInterface.py", line 284, in main_loop
    self.remove_rule(datapath, event)
  File "/home/sdx/dev/localctlr/RyuTranslateInterface.py", line 1239, in remove_rule
    raise e
TypeError: 'NoneType' object is not iterable

Traceback (most recent call last):
  File "LocalController.py", line 449, in <module>
    lc._main_loop()
  File "LocalController.py", line 200, in _main_loop
    self.remove_rule_sdxmsg(msg)
  File "LocalController.py", line 345, in remove_rule_sdxmsg
    self.rule_table[cookie]['status'] = RULE_STATUS_DELETING
KeyError: 196
```

Below is what I think is happening: 

Part one of the failure: Upon reconnection, the SDX controller associates the new connection with the LC [here](https://github.com/atlanticwave-sdx/atlanticwave-proto/blob/persistence/sdxctlr/SDXController.py#L190). When the heartbeat failure hits, there's some [cleanup](https://github.com/atlanticwave-sdx/atlanticwave-proto/commit/e3dc89ee05872d882c29c8941e9474f187c51129#diff-cee6a4957a6f587b92464c25c4e18a9f). This cleanup is being sent to the LC causing the issue. 

Part two of the failure: whatever's happening on the LC side. This part is what I was focusing fruitlessly on Friday. The remove messages are for things that don't exist, which is where I think the failure in RyuTranslateInterface.py is coming from. Why they passed from the LC itself... I'm not clear on. 

Part one is the important part. The second part should be looked at, mainly to have the LC *only* send removal requests that exist.

**Comment by sdonovan1985** [comment]
```
>>>> RECEIVED REMOVE: ['INITIAL_RULES', 'MAIN_PHASE']-['cookie', 'switch_id']-{'cookie': 223, 'switch_id': 1}
>>>>     JSON {'REMOVE': {'cookie': 223, 'switch_id': 1}}


Received a <class 'shared.SDXControllerConnectionManagerConnection.SDXMessageRemoveRule'> message from Connection:
  address:     127.0.0.1
  port:        5555
  recv_cb:     None
  recv_thread: None
  sock:        <eventlet.greenio.base.GreenSocket object at 0x7f991401b350>

Traceback (most recent call last):
  File "LocalController.py", line 449, in <module>
    lc._main_loop()
  File "LocalController.py", line 200, in _main_loop
    self.remove_rule_sdxmsg(msg)
  File "LocalController.py", line 345, in remove_rule_sdxmsg
    self.rule_table[cookie]['status'] = RULE_STATUS_DELETING
KeyError: 223
```

This is one of the problems with the second part. The LC blows up when a rule that's not known (it's from the previous connection) is asked to be removed.  This needs to be fixed, but it is caused by the SDX Controller sending a remove rule due to the new connection starting. It's not supposed to send  out anything until the connection is fully set up, but I mustn't've set that up correctly yet.

**Comment by sdonovan1985** [comment]
Just figured out the first problem: We needed to dissociate the connection in the SDXControllerConnectionManager. This was an oversight, as there was a note to do just this in the comments in SDXControler._handle_connection_loss(). 

The second problem I'm going to start working on now. I think it's mostly going to be a log-and-drop.

I'll be checking in the fix for the first part later today, after removing a lot of debug print statements.

**Comment by sdonovan1985** [comment]
The second part was pretty trivial. Tested.
